# Site settings
title: Hofstra DRC
email: jamiefolsom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The DRC collaborates with faculty at Hofstra in the design and implementation of digital solutions to challenges in humanistic inquiry.
baseurl: "/drc" # the subpath of your site, e.g. /blog/
url: "http://hofstra.github.io/drc" # the base hostname & protocol for your site
twitter_username: hofstradrc
github_username:  hofstra

# Build settings
markdown: kramdown
