---
title: The Digital Research Center at Hofstra
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jamiefolsom@gmail.com
description: The DRC collaborates with faculty at Hofstra in the design and implementation
  of digital solutions to challenges in humanistic inquiry.
baseurl: ''
url: http://hofstradrc.org/
twitter_username: hofstradrc
github_username: hofstra
markdown: kramdown
excerpt_separator: "<!--more-->"
permalink: none
exclude:
- drc-website.sublime-project
